name: First workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: print greeting
        run: |
          echo "Hello World"
          echo "Wonderful life!"
      - name: Print goodby
        run: echo "Done - bye!"
